// AUTO-GENERATED from a per-project-page re-scrape (full galleries) + exact /completed-projects/ thumbnails.
export type ProjectMedia = { thumb: string; hero: string; gallery: string[] }
export const projectImages: Record<string, ProjectMedia> = {
  "killara": {
    "thumb": "/img/proj/killara/thumb-Header-2.jpg",
    "hero": "/img/proj/killara/00-Header-2.jpg",
    "gallery": [
      "/img/proj/killara/00-Header-2.jpg",
      "/img/proj/killara/01-IMG-1142-1.jpg",
      "/img/proj/killara/02-IMG-1143-1.jpg",
      "/img/proj/killara/03-IMG-1149-1.jpg",
      "/img/proj/killara/04-IMG-3343-2.jpg",
      "/img/proj/killara/05-IMG-3410-1.jpg",
      "/img/proj/killara/06-IMG-3411-1.jpg",
      "/img/proj/killara/07-IMG-3412-1.jpg",
      "/img/proj/killara/08-IMG-3413-1.jpg",
      "/img/proj/killara/09-IMG-3414-1.jpg",
      "/img/proj/killara/10-IMG-3416-1.jpg",
      "/img/proj/killara/11-IMG-3417-1.jpg",
      "/img/proj/killara/12-IMG-3418-1.jpg",
      "/img/proj/killara/13-IMG-3419.jpg",
      "/img/proj/killara/14-IMG-3421-1.jpg",
      "/img/proj/killara/15-IMG-3422-1.jpg",
      "/img/proj/killara/16-IMG-3430-1.jpg",
      "/img/proj/killara/17-IMG-3431-1.jpg",
      "/img/proj/killara/18-IMG-3432.jpg"
    ]
  },
  "patrick": {
    "thumb": "/img/proj/patrick/thumb-Header.jpg",
    "hero": "/img/proj/patrick/00-Header.jpg",
    "gallery": [
      "/img/proj/patrick/00-Header.jpg",
      "/img/proj/patrick/01-IMG-1126.jpg",
      "/img/proj/patrick/02-IMG-1127.jpg",
      "/img/proj/patrick/03-IMG-1129.jpg",
      "/img/proj/patrick/04-IMG-1130.jpg",
      "/img/proj/patrick/05-IMG-1133.jpg",
      "/img/proj/patrick/06-IMG-1135.jpg",
      "/img/proj/patrick/07-IMG-1142.jpg",
      "/img/proj/patrick/08-IMG-3436.jpg",
      "/img/proj/patrick/09-IMG-3437.jpg",
      "/img/proj/patrick/10-IMG-3446.jpg",
      "/img/proj/patrick/11-IMG-3450-1.jpg",
      "/img/proj/patrick/12-IMG-3451.jpg",
      "/img/proj/patrick/13-IMG-3452.jpg"
    ]
  },
  "lurline": {
    "thumb": "/img/proj/lurline/thumb-WWA8988-scaled.jpg",
    "hero": "/img/proj/lurline/00-Website-New-Project-Header-Image-Template.jpeg",
    "gallery": [
      "/img/proj/lurline/00-Website-New-Project-Header-Image-Template.jpeg",
      "/img/proj/lurline/01-DSC-0611.jpg",
      "/img/proj/lurline/02-WWA8990.jpg",
      "/img/proj/lurline/03-WWA9063.jpg",
      "/img/proj/lurline/04-WWA9090.jpg",
      "/img/proj/lurline/05-WWA9103.jpg",
      "/img/proj/lurline/06-WWA9107.jpg",
      "/img/proj/lurline/07-WWA9120.jpg",
      "/img/proj/lurline/08-WWA9124.jpg",
      "/img/proj/lurline/09-WWA9140.jpg",
      "/img/proj/lurline/10-DSC-0027.jpg",
      "/img/proj/lurline/11-DSC-0073.jpg",
      "/img/proj/lurline/12-DSC-0174.jpg",
      "/img/proj/lurline/13-DSC-0526.jpg",
      "/img/proj/lurline/14-DSC-0558.jpg",
      "/img/proj/lurline/15-DSC-0573.jpg",
      "/img/proj/lurline/16-DSC-0610.jpg"
    ]
  },
  "sorrento": {
    "thumb": "/img/proj/sorrento/thumb-WWA4320-2-scaled.jpg",
    "hero": "/img/proj/sorrento/00-WWA3965-2-scaled.jpg",
    "gallery": [
      "/img/proj/sorrento/00-WWA3965-2-scaled.jpg",
      "/img/proj/sorrento/01-WWA3965-2.jpg",
      "/img/proj/sorrento/02-WWA4004-2-scaled.jpg",
      "/img/proj/sorrento/03-WWA4036-2-scaled.jpg",
      "/img/proj/sorrento/04-WWA4062-scaled.jpg",
      "/img/proj/sorrento/05-WWA4214-2-scaled.jpg",
      "/img/proj/sorrento/06-WWA4265-scaled.jpg",
      "/img/proj/sorrento/07-Screenshot-2024-06-24-at-3.00.38-pm.png",
      "/img/proj/sorrento/08-Screenshot-2024-06-24-at-3.14.43-pm.png",
      "/img/proj/sorrento/09-WWA4320-2-scaled.jpg",
      "/img/proj/sorrento/10-WWA4575-2-scaled.jpg",
      "/img/proj/sorrento/11-WWA4580-2-scaled.jpg",
      "/img/proj/sorrento/12-WWA4632-2-scaled.jpg",
      "/img/proj/sorrento/13-WWA4737-scaled.jpg",
      "/img/proj/sorrento/14-WWA4764-2-scaled.jpg",
      "/img/proj/sorrento/15-WWA4781-2-scaled.jpg"
    ]
  },
  "branga": {
    "thumb": "/img/proj/branga/thumb-Header-1.jpg",
    "hero": "/img/proj/branga/00-Header-1.jpg",
    "gallery": [
      "/img/proj/branga/00-Header-1.jpg",
      "/img/proj/branga/01-COPA-3-1.jpg",
      "/img/proj/branga/02-COPA-5-1.jpg",
      "/img/proj/branga/03-COPA-12-1.jpg",
      "/img/proj/branga/04-COPA-15-1.jpg",
      "/img/proj/branga/05-COPA-20-1.jpg",
      "/img/proj/branga/06-COPA-21-1.jpg",
      "/img/proj/branga/07-COPA-31-1.jpg",
      "/img/proj/branga/08-COPA-37-1.jpg",
      "/img/proj/branga/09-COPA-43-1.jpg",
      "/img/proj/branga/10-COPA-46-1.jpg",
      "/img/proj/branga/11-COPA-50-1.jpg",
      "/img/proj/branga/12-COPA-63-1.jpg",
      "/img/proj/branga/13-COPA-69-1.jpg",
      "/img/proj/branga/14-COPA-75-1.jpg"
    ]
  },
  "red-cedar": {
    "thumb": "/img/proj/red-cedar/thumb-RedCedar-112.jpg",
    "hero": "/img/proj/red-cedar/00-Red-Cedar-Studio-Header-Image.jpg",
    "gallery": [
      "/img/proj/red-cedar/00-Red-Cedar-Studio-Header-Image.jpg",
      "/img/proj/red-cedar/01-LOU-Projects-April-2021-89.jpg",
      "/img/proj/red-cedar/02-LOU-Projects-April-2021-90-1.jpg",
      "/img/proj/red-cedar/03-LOU-Projects-April-2021-93-1.jpg",
      "/img/proj/red-cedar/04-LOU-Projects-April-2021-96-1.jpg",
      "/img/proj/red-cedar/05-LOU-Projects-April-2021-97-1.jpg",
      "/img/proj/red-cedar/06-LOU-Projects-April-2021-102-1.jpg",
      "/img/proj/red-cedar/07-LOU-Projects-April-2021-103-1.jpg",
      "/img/proj/red-cedar/08-LOU-Projects-April-2021-106-1.jpg",
      "/img/proj/red-cedar/09-LOU-Projects-April-2021-108-1.jpg",
      "/img/proj/red-cedar/10-LOU-Projects-April-2021-116-1.jpg",
      "/img/proj/red-cedar/11-LOU-Projects-April-2021-119-1.jpg",
      "/img/proj/red-cedar/12-LOU-Projects-April-2021-120-1.jpg",
      "/img/proj/red-cedar/13-LOU-Projects-April-2021-126-1.jpg"
    ]
  },
  "pymble": {
    "thumb": "/img/proj/pymble/thumb-pymble-lou-projects-hero.webp",
    "hero": "/img/proj/pymble/00-pymble-lou-projects-banner.webp",
    "gallery": [
      "/img/proj/pymble/00-pymble-lou-projects-banner.webp",
      "/img/proj/pymble/01-pymble-lou-projects-1.webp",
      "/img/proj/pymble/02-pymble-lou-projects-2.webp",
      "/img/proj/pymble/03-pymble-lou-projects-3.webp",
      "/img/proj/pymble/04-pymble-lou-projects-4.webp",
      "/img/proj/pymble/05-pymble-lou-projects-5.webp",
      "/img/proj/pymble/06-pymble-lou-projects-6.webp",
      "/img/proj/pymble/07-pymble-lou-projects-7.webp",
      "/img/proj/pymble/08-pymble-lou-projects-8.webp",
      "/img/proj/pymble/09-pymble-lou-projects-9.webp",
      "/img/proj/pymble/10-pymble-lou-projects-10.webp",
      "/img/proj/pymble/11-pymble-lou-projects-11.webp",
      "/img/proj/pymble/12-pymble-lou-projects-12.webp",
      "/img/proj/pymble/13-pymble-lou-projects-13.webp",
      "/img/proj/pymble/14-pymble-lou-projects-14.webp",
      "/img/proj/pymble/15-pymble-lou-projects-15.webp",
      "/img/proj/pymble/16-pymble-lou-projects-hero.webp"
    ]
  },
  "charlton": {
    "thumb": "/img/proj/charlton/thumb-1.-Project-Page-Header.jpg",
    "hero": "/img/proj/charlton/00-2.-Individual-Project-Page-Header.jpg",
    "gallery": [
      "/img/proj/charlton/00-2.-Individual-Project-Page-Header.jpg",
      "/img/proj/charlton/01-Charlton-House-8803.jpg",
      "/img/proj/charlton/02-Charlton-House-8809.jpg",
      "/img/proj/charlton/03-Charlton-House-8881.jpg",
      "/img/proj/charlton/04-Charlton-House-9025.jpg",
      "/img/proj/charlton/05-Charlton-House-9165.jpg",
      "/img/proj/charlton/06-Charlton-House-9198.jpg",
      "/img/proj/charlton/07-Charlton-House-9201.jpg",
      "/img/proj/charlton/08-Charlton-House-9235.jpg",
      "/img/proj/charlton/09-Charlton-House-9275.jpg",
      "/img/proj/charlton/10-Charlton-House-9294.jpg",
      "/img/proj/charlton/11-Charlton-House-9376.jpg",
      "/img/proj/charlton/12-Charlton-House-9325.jpg"
    ]
  },
  "marrowbone": {
    "thumb": "/img/proj/marrowbone/thumb-Website-New-Project-Header-Image-Template-1.jpeg",
    "hero": "/img/proj/marrowbone/00-Pokolbin-Pool-House.jpg",
    "gallery": [
      "/img/proj/marrowbone/00-Pokolbin-Pool-House.jpg",
      "/img/proj/marrowbone/01-HUNTER-7.jpg",
      "/img/proj/marrowbone/02-HUNTER-8.jpg",
      "/img/proj/marrowbone/03-HUNTER-10.jpg",
      "/img/proj/marrowbone/04-HUNTER-12-1.jpg",
      "/img/proj/marrowbone/05-HUNTER-13.jpg",
      "/img/proj/marrowbone/06-HUNTER-15.jpg",
      "/img/proj/marrowbone/07-HUNTER-20.jpg",
      "/img/proj/marrowbone/08-HUNTER-28.jpg",
      "/img/proj/marrowbone/09-HUNTER-29-1.jpg",
      "/img/proj/marrowbone/10-HUNTER-33.jpg",
      "/img/proj/marrowbone/11-HUNTER-42-1.jpg",
      "/img/proj/marrowbone/12-HUNTER-44-1.jpg",
      "/img/proj/marrowbone/13-HUNTER-45-1.jpg",
      "/img/proj/marrowbone/14-HUNTER-47-1.jpg",
      "/img/proj/marrowbone/15-HUNTER-49-1.jpg",
      "/img/proj/marrowbone/16-HUNTER-50-1.jpg",
      "/img/proj/marrowbone/17-HUNTER-52-1.jpg",
      "/img/proj/marrowbone/18-HUNTER-54-1.jpg",
      "/img/proj/marrowbone/19-HUNTER-59-1.jpg",
      "/img/proj/marrowbone/20-HUNTER-61-1.jpg",
      "/img/proj/marrowbone/21-HUNTER-64.jpg",
      "/img/proj/marrowbone/22-HUNTER-68-1.jpg",
      "/img/proj/marrowbone/23-HUNTER-97.jpg",
      "/img/proj/marrowbone/24-HUNTER-99.jpg"
    ]
  },
  "ahara": {
    "thumb": "/img/proj/ahara/thumb-AharaHouse-109.jpg",
    "hero": "/img/proj/ahara/00-Ahara-House-main.jpg",
    "gallery": [
      "/img/proj/ahara/00-Ahara-House-main.jpg",
      "/img/proj/ahara/01-AharaHouse-3-1.jpg",
      "/img/proj/ahara/02-AharaHouse-15-1.jpg",
      "/img/proj/ahara/03-AharaHouse-21-1.jpg",
      "/img/proj/ahara/04-AharaHouse-24-1.jpg",
      "/img/proj/ahara/05-AharaHouse-27-1.jpg",
      "/img/proj/ahara/06-AharaHouse-28-1.jpg",
      "/img/proj/ahara/07-AharaHouse-30-1.jpg",
      "/img/proj/ahara/08-AharaHouse-55-1.jpg",
      "/img/proj/ahara/09-AharaHouse-58-1.jpg",
      "/img/proj/ahara/10-AharaHouse-64-1.jpg",
      "/img/proj/ahara/11-AharaHouse-70-1.jpg",
      "/img/proj/ahara/12-AharaHouse-76-1.jpg",
      "/img/proj/ahara/13-AharaHouse-81-1.jpg",
      "/img/proj/ahara/14-AharaHouse-84-1.jpg",
      "/img/proj/ahara/15-AharaHouse-87-1.jpg",
      "/img/proj/ahara/16-AharaHouse-90-1.jpg",
      "/img/proj/ahara/17-AharaHouse-93-1.jpg",
      "/img/proj/ahara/18-AharaHouse-103.jpg",
      "/img/proj/ahara/19-AharaHouse-106-1.jpg"
    ]
  },
  "gugandi": {
    "thumb": "/img/proj/gugandi/thumb-narara-3.jpg",
    "hero": "/img/proj/gugandi/00-narara-27-1.jpg",
    "gallery": [
      "/img/proj/gugandi/00-narara-27-1.jpg",
      "/img/proj/gugandi/01-narara-1-1.jpg",
      "/img/proj/gugandi/02-narara-3-1.jpg",
      "/img/proj/gugandi/03-narara-4-1.jpg",
      "/img/proj/gugandi/04-narara-15-1.jpg",
      "/img/proj/gugandi/05-narara-16-1.jpg",
      "/img/proj/gugandi/06-narara-33-1.jpg",
      "/img/proj/gugandi/07-narara-36-1.jpg",
      "/img/proj/gugandi/08-narara-39-1.jpg",
      "/img/proj/gugandi/09-narara-43-1.jpg",
      "/img/proj/gugandi/10-narara-45-1.jpg",
      "/img/proj/gugandi/11-narara-53-1.jpg",
      "/img/proj/gugandi/12-narara-56-1.jpg",
      "/img/proj/gugandi/13-narara-57.jpg",
      "/img/proj/gugandi/14-narara-28-1.jpg"
    ]
  },
  "maitland": {
    "thumb": "/img/proj/maitland/thumb-Springfield-Header-Image.jpeg",
    "hero": "/img/proj/maitland/00-Springfield-Header-Image.jpeg",
    "gallery": [
      "/img/proj/maitland/00-Springfield-Header-Image.jpeg",
      "/img/proj/maitland/01-Springfield-House-7.jpg",
      "/img/proj/maitland/02-Springfield-House-26.jpg",
      "/img/proj/maitland/03-Springfield-House-9.jpg",
      "/img/proj/maitland/04-Springfield-House-29.jpg",
      "/img/proj/maitland/05-Springfield-House-12.jpg",
      "/img/proj/maitland/06-Springfield-House-96.jpg",
      "/img/proj/maitland/07-Springfield-House-16.jpg",
      "/img/proj/maitland/08-Springfield-House-23.jpg",
      "/img/proj/maitland/09-Springfield-House-52.jpg",
      "/img/proj/maitland/10-Springfield-House-41.jpg",
      "/img/proj/maitland/11-Springfield-House-42.jpg",
      "/img/proj/maitland/12-Springfield-House-45.jpg",
      "/img/proj/maitland/13-Springfield-House-49.jpg",
      "/img/proj/maitland/14-Springfield-House-66.jpg",
      "/img/proj/maitland/15-Springfield-House-85.jpg",
      "/img/proj/maitland/16-Springfield-House-90.jpg",
      "/img/proj/maitland/17-Springfield-House-103.jpg"
    ]
  },
  "maitland-granny": {
    "thumb": "/img/proj/maitland-granny/thumb-Springfield-Granny-Flat-2.jpg",
    "hero": "/img/proj/maitland-granny/00-Springfield-Granny-Flat-2.jpg",
    "gallery": [
      "/img/proj/maitland-granny/00-Springfield-Granny-Flat-2.jpg",
      "/img/proj/maitland-granny/01-1.-PROJECT-PAGE-IMAGE-2.jpg",
      "/img/proj/maitland-granny/02-Springfield-Granny-Flat-1.jpg",
      "/img/proj/maitland-granny/03-Springfield-House-114-1.jpg",
      "/img/proj/maitland-granny/04-Springfield-House-115-1.jpg",
      "/img/proj/maitland-granny/05-Springfield-House-117-1.jpg",
      "/img/proj/maitland-granny/06-Springfield-House-127-1.jpg",
      "/img/proj/maitland-granny/07-Springfield-House-129-1.jpg",
      "/img/proj/maitland-granny/08-Springfield-House-131-1.jpg",
      "/img/proj/maitland-granny/09-Springfield-House-141-1.jpg",
      "/img/proj/maitland-granny/10-Springfield-House-142-1.jpg",
      "/img/proj/maitland-granny/11-Springfield-House-144-1.jpg"
    ]
  },
  "mandalong": {
    "thumb": "/img/proj/mandalong/thumb-Header-5.jpg",
    "hero": "/img/proj/mandalong/00-Header-5.jpg",
    "gallery": [
      "/img/proj/mandalong/00-Header-5.jpg",
      "/img/proj/mandalong/01-please-photoshop-watermark.jpg",
      "/img/proj/mandalong/02-please-photoshop-watermark1.jpg",
      "/img/proj/mandalong/03-1.-HEADER-with-water-mark-photoshopped-out-please.jpg",
      "/img/proj/mandalong/04-Dooralong-079.jpg",
      "/img/proj/mandalong/05-LOU-Projects-April-2021-7.jpg",
      "/img/proj/mandalong/06-LOU-Projects-April-2021-18.jpg",
      "/img/proj/mandalong/07-LOU-Projects-April-2021-20.jpg",
      "/img/proj/mandalong/08-LOU-Projects-April-2021-22.jpg",
      "/img/proj/mandalong/09-LOU-Projects-April-2021-25.jpg",
      "/img/proj/mandalong/10-LOU-Projects-April-2021-35.jpg",
      "/img/proj/mandalong/11-LOU-Projects-April-2021-40.jpg",
      "/img/proj/mandalong/12-LOU-Projects-April-2021-44.jpg",
      "/img/proj/mandalong/13-LOU-Projects-April-2021-46.jpg",
      "/img/proj/mandalong/14-LOU-Projects-April-2021-72.jpg"
    ]
  }
}
