// AUTO-GENERATED verbatim project synopsis copy (scraped 1:1 from each project page).
export const projectCopy: Record<string, string[]> = {
  "killara": [
    "The design of the house includes native and renewable materials such as the handmade front door by Bib’n Brace, handcrafted vanities by Woodman Designs, and basins sourced from Concrete Nation. A custom kitchen supplied and installed by Vogue Kitchens. As well as blackbutt timber floors supplied by Carpet One Central Coast, which consist of a 4mm hardwood veneer, meaning it can be sanded several times in its lifetime and has the look and feel of the real thing.",
    "The orientation of the house is important and the overhang of the roof ensures no sun enters the house during peak hours in summer, while letting direct sunlight into the house during winter. Keeping sun out in summer keeps the house naturally cooler, while letting sun in in winter warms the concrete slab during the day which continues to radiate heat during the night."
  ],
  "patrick": [
    "The house is designed as a U shape, to provide privacy from the east, south and west sides, and in the middle a generous amount of timber decking for entertaining. Landscaping also plays a vital role in the general feel of the Patrick House and adds to the cooling and shading where necessary. At the rear, there is a big beautiful Australian Red Cedar tree, which was preserved during the construction process providing privacy and protection. While at the front, our landscaper from Ocean Landscapes planted a Japanese Maple to provide shade to the entertaining area in the summer and in the winter when the leaves shed, sunlight will flow in.",
    "The orientation of the house is also important and the overhang of the roof ensures no sun enters the house during peak hours in summer, while letting direct sunlight into the house during winter. Keeping sun out in summer keeps the house naturally cooler, while letting sun in in winter warms the concrete slab during the day which continues to radiate heat during the night."
  ],
  "lurline": [
    "The renovation/extension of this property was driven by the need to accommodate a growing family. The clients’ desire to preserve the front facade’s quaint appeal, while introducing a striking modern extension to the rear, was central to the design brief.",
    "Lou Projects were involved early on in the design, providing the clients with expert guidance, and ensuring informed decisions aligned with budgetary and design considerations. This collaborative approach enabled the project to start on time and be completed on budget.",
    "The extension at the rear consisted of a new kitchen and living area, seamlessly connected to a spacious undercover deck. A second storey was added to the existing house, where the master bedroom and ensuite is now located – almost like a parent’s retreat.",
    "The renovation of the existing house focused on enhancing the performance and comfort of the home, with the installation of blow-in insulation, double glazed UPVC windows, and a HRV unit providing continuous, filtered airflow throughout the home. To top it all off, new flooring, decking, screening, roofing, rendering and a fresh coat of paint, brought the existing house back to life/breathed new life into the existing home."
  ],
  "sorrento": [
    "The home needed to be extremely energy efficient and produce more energy than it consumes, ensuring longevity of the house for ongoing costs to live in it when they retire.",
    "The build included the demolition of the existing house, to create a blank canvas for us to build a new healthy home. Some key design features included the need to capitalise on the water views, where they would spend a lot of time having BBQs and swimming in the pool on the back deck right on the waterfront.",
    "To create a healthy and high performing home, we focused on insulation, airtightness and ventilation. The home was built out of SIPs (structural insulated panels), sourced from Smart SIPs Australia. SIPs are prefabricated, ready to assemble panels that provide strength and durability. They’re also an eco-friendly building material, that reduce waste onsite due to being precision cut before arrival, and perhaps most importantly, create a more energy efficient home relying less on heating and cooling. They do this by providing a consistent layer of insulation and airtightness. The majority of the SIPs panels used in Sorrento House boast an impressive R-value of 8.2, with others ranging from R-values of 6.2 to 4.2. This significantly exceeds the insulation levels of traditional construction methods.",
    "For additional support, structural steel was incorporated into the SIPs structure and insulated on the outside to reduce thermal bridging. Thermal bridges are weak points in the building envelope that allow heat to pass through more easily, and they occur where materials that are better conductors of heat form a ‘bridge’ between the interior and exterior face of the home. In this case, insulating around the outside of the structural steel beams diminished the gap in the insulation layer of the home and reduced the potential for heat loss and/or gain.",
    "The whole frame was then wrapped in a vapour permeable wrap, from our good friends at pro clima, where every window and penetration was taped and sealed, then water tested to ensure durability. Because, as we’ve discussed previously, water/moisture is what causes the most damage to the frame.",
    "To further enhance thermal performance, Sorrento House features UPVC double glazed windows and doors, sourced from Mint Windows and Doors – you can learn more about different frames and glazing options on our blog. These windows and doors contribute to a high performing, energy efficient environment, keeping the home warm in winter and cool in summer. The inclusion of quality airtight seals ensures minimal air leakage and maximises energy efficiency.",
    "To ensure proper ventilation and superior indoor air quality, Sorrento House is equipped with a whole-house HRV (heat recovery ventilation) system, from Vector HRV. In basic terms, a HRV system is a smart ventilation system designed to bring in fresh air 24/7 without significant energy losses. This is coupled with an air conditioner installed throughout the home, which will only be required in more extreme temperatures.",
    "A big sustainable feature of this home is the state-of-the-art 12.47kW solar battery system, supplied and installed by Eco Sparky. Designed with full home backup capability, this system ensures the battery charges from the solar panels even when the grid is down, keeping the home seamlessly powered. The system also partners with an app that enables intensive system monitoring, ensuring optimal performance and providing real-time insights into the home’s energy usage.",
    "Some big construction considerations included the use of screw piles under the footings as well as galvanised screw piles for the raised floor sections. This was required due to the instability of the soil and the floor levels needed to be above flood levels.",
    "Another highlight feature of this build, and something we’d never done before, was creating a turntable in the driveway to accommodate the tight access at the front of the home. As well as a beautiful precast pool that was craned onto site.",
    "The result is a beautiful Hamptons style waterfront home, comfortable and enjoyable to live in all year round."
  ],
  "branga": [
    "One of the main features of the project was a major extension, converting the existing master bedroom to a new lounge/living area. This included building a new deck and roof with an outdoor BBQ area to provide a seamless indoor/outdoor space to overlook the pool and beautiful trees surrounding the property. A new kitchen was also installed, including space for a butlers pantry behind the kitchen. While the floors were upgraded to new engineered spotted gum flooring by Hurfords, and some beautiful carpet in the bedrooms to soften these areas.",
    "To improve the performance of the home we addressed three main areas: insulation, the building envelope, and ventilation. All ceilings, floors and walls were lined with new insulation, ensuring a very well insulated and cosy home no matter what season.",
    "All windows and doors were replaced with brand new windows and doors by Logikhaus. These windows and doors are made in Poland. They have a timber frame with external aluminium cladding for enhanced durability and aesthetics. They are double glazed and made at the highest quality (learn more about double glazing and frame options on our blog).",
    "A heat recovery ventilation system was also installed to bring fresh air into the house when all windows and doors are closed. As most air leaks were addressed during the renovation, it was important to now include constant mechanical ventilation to bring in fresh air from outside at the same temperature as inside so the temperature of the home remains comfortable and consistent.",
    "Overall, this resulted in a cosy, functional and energy efficient, newly renovated home. We’d like to thank the Master Builders Association for recognising this, and awarding us the winner of the ‘Energy Efficiency and Environmental Sustainability’ category in the 2022 Newcastle Excellence in Building Awards, click here to learn more."
  ],
  "red-cedar": [
    "The studio is set in a Flame Zone area, which required both the design and build to have careful considerations for the types of materials used in order to comply with the stringent requirements of the Bushfire Code.",
    "The studio has 2 bedrooms and 1 bathroom with separate living quarters. These quarters are divided by a big open thoroughfare and covered slab patio, this design was to maximise the views from the existing house to the beautiful bush behind.",
    "Some of the key materials used include Pro Clima wall and roof wraps, recycled bricks from The Brick Pit, double glazed windows and doors and stainless steel fire shutters."
  ],
  "pymble": [
    "This project focused on transforming the backyard into a space that feels connected, functional, and easy to use day-to-day.",
    "The key move was opening up the rear of the home. New floor-to-ceiling sliding glass doors create a direct link between the internal living areas and the outdoor space, allowing everything to flow together more naturally.",
    "Outside, the layout was designed to support both entertaining and family life. A cantilevered steel awning provides cover to the main outdoor zone, with a built-in concrete BBQ positioned as a simple, durable centrepiece.",
    "The backyard steps down through a series of concrete amphitheatre-style levels, helping manage the change in height while also creating informal seating and usable space. The new tiled pool sits within this, becoming a central part of how the backyard is used.",
    "At the front, the entry and driveway were updated to match the rest of the project. A rolling timber slat gate adds privacy while still keeping a warm, approachable feel.",
    "One of the defining aspects of the project is the contrast between old and new. The original cottage remains visible at the upper level, while the rear introduces a more modern, robust set of materials. Rather than competing, the two work together to show how the house has evolved over time.",
    "The result is a backyard that’s simple, practical, and built to be used – whether that’s for entertaining, relaxing, or letting the kids take over."
  ],
  "charlton": [
    "The intention for Charlton House was to build something special for the retirement of our clients. It had to be completely different from the rest of the existing house, so that it felt like their very own slice of paradise.",
    "The project included some renovation to the existing, dual occupancy, two-storey home, but focused on adding a new 1 bedroom, 1 bathroom, separate dwelling to the front end of the house.",
    "The juxtaposition of the existing to new was key to the design brief, however the main focus and priority was to work with the already existing and thriving garden that had been established on the block. The clients wanted to create a seamless connection with the garden outdoors and create that feeling of bringing the outside in and the inside out. We understood this from the very beginning, and took particular care during the entire build to keep the plants alive and strong.",
    "As you’ll see in the video below, our clients were so happy with the final result. It seems as though the house was built years ago and the garden was established around it, but in fact, it was the other way round, the garden was here and established, and the house has been built beautifully to nestle inside it.",
    "Some of the striking features of this extension include the use of Western Red Cedar cladding, supplied by Modinex, externally and on the ceilings inside, as well as a handmade Western Red Cedar pivot front door. There’s also the seamless transition between the internal and external linings which you see through the clerestory windows.",
    "The raked glazing on the front facade of the house has both aesthetic and functional impacts on the home. It not only creates a striking, modern look, and enhances the sense of openness and connection to the outdoors, it’s also one of the special detailings used to improve the performance of the home by utilising passive solar principles – due to the orientation, it optimises sunlight in winter and reduces excessive sunlight in summer, allowing for natural light and heat control.",
    "The exposed powder-coated, cantilever awnings have a similar impact. Both the cantilever design and the exposed framework adds to the visual appeal and striking, modern look of the home. With the added benefits of the floating awnings providing shelter and reducing heat gain inside the home. While the powder-coated finish is durable and provides excellent protection against UV damage, rust and wear.",
    "Another thing we love is the comprehensive joinery in the living room that was designed to cater for an EPIC entertainment system with projector and drop down screen – a music and movie lover’s dream! This was a must for our clients, as the owners of one of Australia’s first audio visual home entertainment stores, and the Central Coast’s home of HiFi music and home cinema, Mcleans Hi-Fi.",
    "The renovation of the existing home included demolition of existing kitchen and bedrooms, completely rebuilding internal walls, installing new windows and relevelling the existing slabs ready for new engineered flooring. The bones of the extension were then built out of structural steel so we could achieve seamless open spaces and cantilever eave details. Some other main features included exposed steel posts located at the corners of the build behind the glass so it looks simplistic. As well as barestone infills internally, which is concrete-looking cladding, used instead of skirting to add an extra bit of texture and class.",
    "Our clients came to us through the recommendation of their architect, Luke Farrugia Architect. We’ve worked with Luke on numerous projects, and the strong and collaborative relationship between Luke Farrugia Architect and Lou Projects is what makes projects like this such a success.",
    "As always, the amazing trades we worked with on this project were a wonderful extension of our team, conducting themselves respectfully onsite and creating beautiful work – thank you Mitch and the team at Copper Electrical, Tom our invaluable painter from Valiant Painting Co, Ben and the team at Totally Drained Plumbing and Dan and the team at Dan Lamond Metal Roofing."
  ],
  "marrowbone": [
    "This dwelling marks Stage 1 of the Pokolbin development, and therefore required the construction of essential infrastructure such as access roads, a spacious shed, a solar and battery system complemented by a backup generator, a wastewater system, and a colossal 365,000L water tank.",
    "Operating entirely off-grid, the property relies on self-generated power and water, both designed to accommodate future expansions. The logistical challenges of this undertaking were considerable, yet the teams from Totally Drained Plumbers and Copper Electrical navigated it all and helped pull it all together.",
    "The pool house itself is enveloped in Pro Clima wraps, ensuring both weather and air-tightness. Additionally, we opted for double glazed UPVC windows from Easy Windows to enhance insulation – you can read more about that here. These windows, along with the lift and slide UPVC doors, not only bolster energy efficiency but also offer superior functionality compared to traditional windows and sliding doors.",
    "We also loved the use of stone wall and floor tiles from Gather Co, appreciating their practicality, durability, and energy efficiency. These tiles effectively retain heat during colder months and provide a cooling effect in warmer weather, contributing to the overall comfort and sustainability of the home."
  ],
  "ahara": [
    "Ahara House is the result of another successful collaboration between Lou Projects and Luke Farrugia Architect, with the interior design guided by Pair Studio. The collaboration among architect, builder, and designer resulted in a cohesive design that considers everything from the positioning of walls and windows to the choice of fixtures and fittings.",
    "Ahara House is a healthy and high performing home that prioritises energy efficiency and mould prevention. The house exceeds standard building practices with its completely waterproof and airtight building envelope, effectively safeguarding against moisture and humidity infiltration that can lead to mould growth and structural damage.",
    "To ensure superior indoor air quality, Ahara House is equipped with a whole-house HRV (heat recovery ventilation) system, from Stiebel Eltron. This advanced system continuously removes stale, moist air from inside, while introducing filtered, fresh air from the outside. The integrated filters effectively eliminate various pollutants, such as pollen, bacteria, smoke, smog, and mould spores. With the ability to adjust the incoming air temperature based on the season, the HRV system provides a consistent supply of clean, filtered air at a comfortable temperature throughout the year.",
    "Additionally, the entire house is outfitted with a Puretec WH2-60 water filter, featuring a dual filtration system that removes chlorine, chemicals, and sediment from the water supply. This ensures that every tap in the house, including showers and sinks, delivers filtered water, offering benefits such as healthier skin and hair, a stronger immune system, and increased wellbeing.",
    "Ahara House prioritises energy efficiency and comfort through exceptional insulation. The use of SIPs (structural insulated panels), sourced from Smart SIPs Australia, provides a highly insulated, airtight frame that enhances durability and energy efficiency. The majority of the SIPs panels used in Ahara House boast an impressive R-value of 8.2, with others ranging from R-values of 6.2 to 4.2. This significantly exceeds the insulation levels of traditional construction methods.",
    "To further enhance thermal performance, Ahara House features timber-framed double glazed windows and doors, sourced from Windoor – you can learn more about different frames and glazing options on our blog. Timber naturally provides insulation, minimising heat/cold transfer between the interior and exterior. Coupled with double glazing, these windows and doors contribute to a high performing, energy efficient environment, keeping the home warm in winter and cool in summer. The inclusion of quality airtight seals ensures minimal air leakage and maximises energy efficiency."
  ],
  "gugandi": [
    "The building standards for this community of homes is set so that each home will achieve a minimum 7 star NatHERS rating, contain photo-voltaic systems producing electricity which will feed into the village’s smart grid, utilise thermally efficient design and construction, as well as the use of recycled and rainwater systems, and natural materials such as mud bricks and recycled timbers.",
    "The project we completed was a unique and exciting mix of all these parameters. The thermally efficient design was well thought out and executed perfectly. This included three different manifestations, depending on the location of the walls. A premium insulation system made from natural wood fibres was installed on the northern side of the home, in a dual layer, to create an R5 rating. This involved a combination of rigid panels and bulk infill from Life Panels. While natural straw bale panels, by Viva Homes, were installed on the southern end of the home, providing additional insulation at the rear of the house and experimenting with other natural materials.",
    "The remaining walls are reverse brick veneer, built with mud bricks by Mudtec. Reverse brick veneer is a system in which the insulation layer is on the outside, and the bricks are on the inside, making the bricks visible from inside the home. Bricks help regulate the temperature of the house via thermal mass, and this system ensures the bricks aren’t influenced by the temperature outside, so they remain a consistent and comfortable temperature inside.",
    "All remaining internal walls were insulated with a high density Life Panel, for sound insulation, creating a peaceful and safe, but also robust and solid feeling inside the home due to the highly insulated and thick walls, floors and ceiling. They were also lined with plywood, for a natural look inside the home. While the external walls are cladded with Weathertex, another high performing, natural wood product.",
    "The windows are double glazed hybrid windows, with an aluminium frame on the outside and western red cedar on the inside, creating the ultimate combination of durability (aluminium) and thermal performance (timber).",
    "Some additional features of the home include a compost toilet, with a great final result achieved by Totally Drained Plumbers. While the flooring is a beautiful combination of recycled timber flooring, by Thor’s Hammer, which looks effortlessly rustic, paired with earth floors, which is hand selected soils and clays mixed in with lime compacted and then sealed with linseed oil so it can breathe. So easy to install the clients did it!",
    "Overall, this was a very interesting and unique project to be a part of, utilising innovative design techniques and a vast array of natural materials."
  ],
  "maitland": [
    "A big consideration for the rebuild was to effectively insulate the walls and ceiling. We decided the most efficient way to do this was to start fresh, by completely stripping the plasterboard and installing quality insulation. The rebuild also included upgrading to high performing double glazed UPVC windows and doors throughout the entire home. Windows and doors are an integral part of the building envelope and can vastly determine the comfort and efficiencies of a building.",
    "Bringing light and nature into the home was our next main intention. This was achieved by designing and constructing a tropical landscaped breezeway opposite the front door. This involved removing part of the existing house to accomodate this space. There are large skylights installed in both bathrooms to allow in an impressive amount of natural sun and moon light, and floor-to-ceiling double glazed windows/doors in the kitchen which overlook a uniquely curved shaped deck with a beautiful garden feature.",
    "The rear garden, along with being beautiful to look at, was a cleverly designed feature. The deck was going to be positioned on the far south side of the site. Inserting the garden feature in between the house and the deck allowed Us to build a high pitched pergola roof north facing, to both cover the deck and provide the perfect amount of shade in summer and sunlight in winter.",
    "The kitchen, designed by Co. Interiors, features a curved timber island bench, gas cooking, integrated dishwasher and oven, and stone bench tops from All Stone & Glass. While each bathroom is an elegant blend of timber, stone and brass features from Loughlin Furniture.",
    "Some integral final finishing touches included a 6.5kw solar system and 5000L water tank."
  ],
  "maitland-granny": [
    "This freestanding granny flat was constructed with a complete weatherproof membrane by Pro Clima paired with external cavity battens for ventilation, and high performing double glazed UPVC windows and doors for added soundproofing and insulation properties. As the flat is raised off the ground, we ensured every nook, including the floor, was insulated. Insulating the floor is an important detail to consider when designing a high performing and cosy home.",
    "The interior features a spacious open plan design with a butterfly style roof, unique tilt and turn windows to open up the space, and custom birch ply skylight windows to allow in stunning views of nature and plenty of natural light. The modern timber kitchen was designed by Co. Interiors.",
    "The exterior features exposed white rafters paired with natural cypress cladding to create a distinct and sophisticated look. While the entertaining deck overlooks a beautifully grassed and landscaped outdoor area."
  ],
  "mandalong": [
    "A new rural house on a highly exposed site where extreme temperatures and winds are the norm. The design is underpinned by both passive and technological environmental strategies and is completely off-grid (power, water and wastewater). Materials are left in their natural state and, as much as possible, have been sourced through reclamation.",
    "Some of the key materials used include cypress cladding from Golden Cypress as it’s one of the most sustainable timber products we could find. Burnished concrete that not only looks amazing but also provides thermal mass which plays a huge role in naturally regulating the temperature of the house. Recycled concrete blocks stacked in a brick pattern that add to the thermal mass again. Double glazed timber windows that have natural insulating properties as well as the ability to capture and store carbon in the process of growing the timber. The house is powered by a 3.3kw solar panel system with 7.5kw of storage in batteries, and utilises the Envirocycle method for treating wastewater.",
    "Architect Luke Furragia played a huge role during the construction process to ensure his vision was understood and the clients were happy."
  ]
}
